config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  namespace :users do
    get '' => 'accounts#index'
    resource :unsubscribes, only: [:edit, :destroy]
  end

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  resources :admin_users, only: [:index, :show, :edit, :update, :destroy]

  resources :products, only: [:index, :show]

  resources :admin_products

  resources :carts, only: [:index, :create, :update, :destroy]


  resources :orders, only: [:index, :new, :create, :update]

  namespace :orders do
    get 'check'
  end

  resources :admin_orders, only: [:index, :show, :update]

  resources :addresses, only: [:new, :create, :edit, :update, :destroy]
  post "/order_addresses" => "addresses#order_create", as: "order_addresses"

  resources :consts, only: [:update]
  namespace :consts do
    get 'edit'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_paranoid

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  def remember_me
    true
  end
  # ユーザー検索メソッド
  def User.search(search)
    if search.present?
      User.where("first_name like ? OR last_name like ? OR (last_name || first_name) like ? OR (last_name || first_name) like?", "%#{search}%","%#{search}%","%#{search}%","%#{search}%")
    else 
      User.all
    end
  end

  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_one :cart, dependent: :destroy
  validates :email, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_ruby, presence: true
  validates :last_name_ruby, presence: true
  validates :phone_number, presence: true, length: { minimum: 10, maximum: 11 }
  validates :zip_code, presence: true, length: { is: 7 }
  validates :address, presence: true
  # 新しいパスワードと確認用パスワードの一致を検証
  validates :password, confirmation: true
end

app/controllers/users/accounts_controller.rb
class Users::AccountsController < ApplicationController
  # マイページ
  def index
    @user = current_user
  end
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true
# Users::PasswordsController < Devise::Controller　=>　Users::PasswordsController < ApplicationController
class Users::PasswordsController < ApplicationController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # ユーザーパスワードの編集
  def edit
    @user = current_user
    @path = user_password_path
  end

  # PUT /resource/password
  # ユーザーパスワード更新
  def update
        @user = current_user
    if  @user.update_with_password(users_params)
        sign_in(@user, bypass: true)
        flash[:success] = "パスワードの更新に成功しました！"
        redirect_to users_path
    else
        @path = user_password_path
        flash[:failure] = "パスワードの更新に失敗しました！"
        render :edit
    end
  end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
  # ストロングパラメーター追加　
  private
  def users_params
    params.require(:user).permit(:password, :password_confirmation, :current_password)
  end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected
  # マイページ編集、更新後のリダイレクト　devise(defaultでroot設定)
  def
    after_update_path_for(resource)
      users_path
  end
  # パスワード無しでマイページ更新　devise(registration)はdefaultでパスワード必須
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  protect_from_forgery
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super

  # end

  def create
      if admin_signed_in?
          sign_out current_admin
      end
      flash[:notice] = "ログインに失敗しました。入力フォームを確認してください。"
      super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/unsubscribes_controller.rb
class Users::UnsubscribesController < ApplicationController

    def edit
        @user = User.find(current_user.id)
    end

    def destroy
        user = User.find(current_user.id)
        user.destroy
        redirect_to root_path
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/accounts/index.html.erb
    <div class="container">
        <div class="col-md-8 mx-auto border rounded shadow-lg bg-light">
            <div class="row border">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-4 mb-md-n3">
                            <em><h2>マイページ</h2></em>

                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <em><%= render "users/list", user: @user %></em>
                            <em><%= link_to "パスワードの変更", edit_user_password_path(@user), class: "btn btn-warning float-right" %></em>
                            <em><%= link_to "編集", edit_user_registration_path(@user), class: "btn btn-success float-right" %></em>
                            <em><a class="btn btn-primary btn-md" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                            追加した住所一覧
                            </a></em>
                        </div>
                    </div>

                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="collapse" id="collapseExample">
                        <div class="card card-body">
                            <table class="table table-hover text-center table-sm">
                                <% @user.addresses.each do |address| %> 
                                <thead>
                                    <tr>
                                        <td></td>
                                        <td><%=address.name %></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td></td>
                                        <td class="align-middle text-left">〒　<%= address.zip_code %></td>
                                        <td class="align-middle text-left"><%= address.address %></td>
                                        <td></td>
                                        <td></td>
                                        <td class="text-right">
                                            <%= link_to "編集", edit_address_path(address.id), class: "btn btn-success text-right " %>
                                            <%= link_to "削除", address_path(address.id), method: :delete, class: "btn btn-danger", data: {confirm: "本当に削除しますか？"}%>
                                        </td>
                                    </tr>
                                    <% end %>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td class="text-right"><%= link_to "新規追加", new_address_path(@user.id), class: "btn btn-info" %></td>
                                    </tr>
                                </tbody>
                            </table>
                    
                            
                    </div>
                </div>
                                    
                        <div class="text-right "><%= link_to "購入履歴", orders_path, class: "btn btn-primary" %>
                        </div>
                                    
                        
                </div>
            </div>
            <%= link_to "退会手続きはこちらから", edit_users_unsubscribes_path %>

        </div>
    </div>