config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  namespace :users do
    get '' => 'accounts#index'
    resource :unsubscribes, only: [:edit, :destroy]
  end

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  resources :admin_users, only: [:index, :show, :edit, :update, :destroy]

  resources :products, only: [:index, :show]

  resources :admin_products

  resources :carts, only: [:index, :create, :update, :destroy]


  resources :orders, only: [:index, :new, :create, :update]

  namespace :orders do
    get 'check'
  end

  resources :admin_orders, only: [:index, :show, :update]

  resources :addresses, only: [:new, :create, :edit, :update, :destroy]
  post "/order_addresses" => "addresses#order_create", as: "order_addresses"

  resources :consts, only: [:update]
  namespace :consts do
    get 'edit'
  end
end

app/controllers/admin_products_controller.rb
class AdminProductsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @products, @length = search_products_data
  end

  def show
    @product = Product.includes(:tracks).order("tracks.disc").order("tracks.number").find(params[:id])
    if @product.summary.empty?
      @product.summary = "※商品紹介はありません"
    end
  end

  def new
    @product = Product.new
    @product.artist = Artist.new
    @product.label  = Label.new
    @product.genre  = Genre.new

    @artists = Artist.all
    @labels  = Label.all
    @genres  = Genre.all
  end

  def create
    @product = Product.new(products_params)

    update_info_data(@product)
    product_save_error = @product.save
    update_track_data(@product)

    # エラー判別
    if product_save_error
      redirect_to admin_product_path(@product), notice: "商品の入力内容が登録されました。"
    else
      flash.now[:notice] = "商品の入力内容を登録できませんでした。入力内容を確認してください。"
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    @artists = Artist.all
    @labels  = Label.all
    @genres  = Genre.all
  end

  def update
    @product = Product.find(params[:id])

    update_info_data(@product)
    product_save_error = @product.update(products_params)
    update_track_data(@product)

    # 商品入力データ保存
    if product_save_error
      redirect_to admin_product_path(@product), notice: "商品の入力内容が登録されました。"
    else
      flash.now[:notice] = "商品の入力内容を登録できませんでした。入力内容を確認してください。"
      render :edit
    end
  end

  def destroy
    product = Product.find(params[:id])
    product.destroy
    redirect_to admin_products_path
  end

  private
  # Strong Parameters
  def products_params
    params.require(:product).permit(:name, :jacket_image, :price, :stock, :summary)
  end
  def artist_params
    params.require(:product).permit(artist: :name)
  end
  def label_params
    params.require(:product).permit(label: :name)
  end
  def genre_params
    params.require(:product).permit(genre: :name)
  end
  def tracks_params
    params.require(:product).permit(tracks: [:disc, :number, :name, :length])[:tracks]
  end

  # トラック更新
  def update_track_data(product)
    # 既存トラック削除
    product.tracks.each {|num|
      unless tracks_params.key?(num['id'].to_s)
        track = Track.find(num['id'])
        track.destroy
      end
    }

    # トラック追加・変更
    tracks_params.each {|key, value|
      if product.tracks.find_by(id: key).nil?
        track = Track.new(value)
        track.product_id = product.id
        track.save
      else
        track = Track.find(key)
        track.update(value)
      end
    }
  end

  # 商品情報更新
  def update_info_data(product)
    # アーティストデータ追加・反映
    artist = Artist.find_by(name: artist_params['artist']['name'])
    if artist.nil?
      artist = Artist.new(artist_params['artist'])
      artist.save
    end
    product.artist_id = artist.id

    # レーベルデータ追加・更新
    label = Label.find_by(name: label_params['label']['name'])
    if label.nil?
      label = Label.new(label_params['label'])
      label.save
    end
    product.label_id = label.id

    # ジャンルデータ追加・更新
    genre = Genre.find_by(name: genre_params['genre']['name'])
    if genre.nil?
      genre = Genre.new(genre_params['genre'])
      genre.save
    end
    product.genre_id = genre.id
  end
end

app/helpers/admin_products_helper.rb
module AdminProductsHelper
end

app/views/admin_products/_edit_product_form.html.erb
<div class="container"><div class="row"><div class="col-lg-9 mx-auto">
  <div class="container">
    <h2><%= page_title %></h2>
  </div>

  <%= form_with model: product, url: post_uri do |product_f| %>
    <div class="container">
      <div class="row">
        <div class="col-4">
          <%= attachment_image_tag product, :jacket_image, fallback: "no_image.png", class: "rounded img-raised", id: "jacketImage" %>
        </div>
        <div class="col">
          <label for="selectImage" class="btn btn-info">
            ジャケット画像を選択
            <%= product_f.attachment_field :jacket_image, id: "selectImage", class: "d-none" %>
          </label>
          <p id="selectImageName" class="ml-2"></p>
        </div>
      </div>
    </div>

    <div class="container mt-5">
      <div class="form-group">
        <%= product_f.label :name, "アルバム名" %>
        <%= product_f.text_field :name, id: "productName", class: "form-control", maxlength: 255 %>
      </div>

      <div class="form-group">
        <%= product_f.fields_for product.artist do |artist_f| %>
          <%= artist_f.label :name, "アーティスト" %>
          <%= artist_f.text_field :name, id: "artistName", class: "form-control", maxlength: 255 %>
        <% end %>
      </div>

      <div class="form-group">
        <%= product_f.fields_for product.label do |label_f| %>
          <%= label_f.label :name, "レーベル" %>
          <%= label_f.text_field :name, id: "labelName", class: "form-control", maxlength: 255 %>
        <% end %>
      </div>

      <div class="form-group">
        <%= product_f.fields_for product.genre do |genre_f| %>
          <%= genre_f.label :name, "ジャンル" %>
          <%= genre_f.text_field :name, id: "genreName", class: "form-control", maxlength: 255 %>
        <% end %>
      </div>

      <div class="form-group row">
        <div class="col">
          <%= product_f.label :price, "価格" %>
          <%= product_f.number_field :price, id: "productPrice", class: "form-control", min: 0 %>
        </div>
        <div class="col">
          <%= product_f.label :stock, "在庫数" %>
          <%= product_f.number_field :stock, id: "productStock", class: "form-control", min: 0 %>
        </div>
      </div>
    </div>

    <div class="container mt-5">
      <table class="table table-sm table-striped">
        <thead class="thead-dark">
          <tr>
            <th></th>
            <th class="align-middle">Disc</th>
            <th class="align-middle">No.</th>
            <th class="align-middle">曲名</th>
            <th class="align-middle">再生時間</th>
            <th class="align-middle"><a id="addTrack" class="btn btn-info">追加</a></th>
          </tr>
        </thead>
        <tbody id="trackRecords">
          <% product.tracks.each do |track| %>
            <tr class="track-item">
              <%= product_f.fields_for "tracks[]", track do |track_f| %>
                <td></td>
                <td class="align-middle"><%= track_f.number_field :disc, class: "form-control track-disc", min: 0, max: 99, placeholder: "Disc" %></td>
                <td class="align-middle"><%= track_f.number_field :number, class: "form-control track-number", min: 0, max: 99, placeholder: "No." %></td>
                <td class="align-middle"><%= track_f.text_field :name, class: "form-control track-name", placeholder: "曲名" %></td>
                <td class="align-middle"><%= track_f.text_field :length, class: "form-control track-length", maxlength: 10, placeholder: "再生時間" %></td>
                <td class="align-middle"><a class="btn btn-danger text-white track-delete">削除</a></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="container mt-5">
      <%= product_f.label :summary, "商品紹介" %>
      <%= product_f.text_area :summary, class: "form-control", style: "min-height: 10em;" %>
    </div>

    <div class="container mt-5"><div class="row">
      <div class="col">
        <% if controller.action_name == "edit" %>
          <%= link_to "商品詳細へ戻る", admin_product_path(product), class: "btn btn-secondary" %>
        <% end %>
      </div>
      <div class="col text-right">
        <a href="#!" id="submitCheck" class="btn btn-success" data-toggle="modal">内容を登録</a>
      </div>
    </div></div>

    <!-- Alert Modal -->
    <div class="modal fade" id="alertModal" tabindex="-1" role="dialog" aria-labelledby="alertModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title text-danger" id="alertModalLabel">確認してください</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <p>入力内容が空欄になっている項目があります。<br/>
            再度入力内容を確認してください。</p>
          </div>
          <div class="modal-footer text-right">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">戻る</button>
          </div>
        </div>
      </div>
    </div>

    <!-- Submit Modal -->
    <div class="modal fade" id="submitModal" tabindex="-1" role="dialog" aria-labelledby="submitModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title text-danger" id="submitModalLabel">入力内容を登録</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <p>入力内容を登録しますか？</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">やめる</button>
            <%= product_f.submit "登録", class: "btn btn-success" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div></div></div>

<script>
  // エンターキーによるSubmitを妨害
  document.onkeypress = enter;
  function enter(){
    if( window.event.keyCode == 13 ){
      return false;
    }
  }

  $(function(){
    // オートコンプリート設置
    var artists = [
      <% artists.each do |artist| %>
        '<%= artist.name %>',
      <% end %>
    ];
    var labels = [
      <% labels.each do |label| %>
        '<%= label.name %>',
      <% end %>
    ];
    var genres = [
      <% genres.each do |genre| %>
        '<%= genre.name %>',
      <% end %>
    ];
    $('#artistName').autocomplete({ source: artists });
    $('#labelName').autocomplete({ source: labels });
    $('#genreName').autocomplete({ source: genres });

    // トラックをソート（最後のレコードのインデックス値取得）
    var last_item = $('.track-item:last');
    if (last_item.length > 0) {
      var last_index = Number(last_item.find('.track-disc').attr('id').match(/\d+/)) + 1;
    } else {
      var last_index = 1;
      add_track();
    }
    sort_track();

    // ファイル制限追加
    $('#selectImage').attr('accept', 'image/jpg,image/jpeg,image/png,image/gif');
    // 画像ファイルとファイル名を表示
    $('#selectImage').on('change', function(element) {
      var reader = new FileReader();
      reader.onload = function(e) {
        $('#jacketImage').attr('src', e.target.result);
        $('#selectImageName').text(element.target.files[0].name);
      }
      reader.readAsDataURL(element.target.files[0]);
    });

    // トラックを追加
    $('#addTrack').on('click', add_track);
    // トラックを削除
    $(document).on('click', '.track-delete', function() {
      $('.track-item').eq($(this).parents('.track-item').index()).remove();
      if ($('.track-item').length <= 0) add_track();
    });
    // トラックをソート（番号変更時）
    $(document).on('blur', '.track-disc, .track-number', sort_track);

    // トラックの追加
    function add_track() {
      var track_disc = Number($('.track-item:last').find('.track-disc').val());
      var track_number = Number($('.track-item:last').find('.track-number').val()) + 1;

      if (isNaN(track_disc)) track_disc = 1;
      if (isNaN(track_number)) track_number = 1;

      $('#trackRecords').append(''
        + '<tr class="track-item">'
          + '<td></td>'
          + '<td class="align-middle">'
            + '<input class="form-control track-disc" min="0" max="99" type="number" value="' + track_disc + '" name="product[tracks][' + last_index + '][disc]" id="product_tracks_' + last_index + '_disc" placeholder="Disc">'
          + '</td>'
          + '<td class="align-middle">'
            + '<input class="form-control track-number" min="0" max="99" type="number" value="' + track_number + '" name="product[tracks][' + last_index + '][number]" id="product_tracks_' + last_index + '_number" placeholder="No.">'
          + '</td>'
          + '<td class="align-middle">'
            + '<input class="form-control track-name" type="text" name="product[tracks][' + last_index + '][name]" id="product_tracks_' + last_index + '_name"  placeholder="曲名">'
          + '</td>'
          + '<td class="align-middle">'
            + '<input class="form-control track-length" maxlength="10" size="10" type="text" name="product[tracks][' + last_index + '][length]" id="product_tracks_' + last_index + '_length" placeholder="再生時間">'
          + '</td>'
          + '<td class="align-middle">'
            + '<a class="btn btn-danger text-white track-delete">削除</a>'
          + '</td>'
        + '</tr>'
      );
      last_index++;
    }

    // 内容の確認ボタンが押された
    $('#submitCheck').on('click', valid_check);

    // トラックのソート
    function sort_track() {
      var table = $('#trackRecords');
      var tracks = $('.track-item');

      tracks.sort(function(a, b) {
        return $(a).find('.track-disc').val() - $(b).find('.track-disc').val() || $(a).find('.track-number').val() - $(b).find('.track-number').val();
      });
      
      table.empty();
      table.append(tracks);
    };

    // バリデーションチェック
    function valid_check() {
      var error_count = 0;
      var targets = ['#productName', '#artistName', '#labelName', '#genreName', '#productPrice', '#productStock', '.track-disc', '.track-number', '.track-name', '.track-length'];

      targets.forEach(function(target) {
        $(target).each(function(index, element) {
          if ($(element).val() == "") {
            $(element).addClass("is-invalid");
            error_count++;
          } else {
            $(element).removeClass("is-invalid");
          }
        });
      });

      // 出現モーダルダイアログの変更
      if (error_count > 0) {
        $('#submitCheck').attr('data-target', '#alertModal');
      } else {
        $('#submitCheck').attr('data-target', '#submitModal');
      }
    }
  });
</script>

app/views/admin_products/_index_products.html.erb
<div class="container mt-4"><div class="row">
  <div class="lead">
    検索結果: <%= products.present? ? length : 0 %>件
  </div>
</div></div>

<div class="container mt-4">
  <% if products.present? %>
    <% products.each do |product| %>
      <% if controller.controller_name == "products" %>
        <% url_path = product_path(product) %>
      <% else %>
        <% url_path = admin_product_path(product) %>
      <% end %>

      <div class="row no-gutters mb-4 p-3 img-raised rounded">
        <div class="col-2">
          <%= link_to url_path do %>
            <%= attachment_image_tag product, :jacket_image, fallback: "no_image.png", class: "rounded", id: "jacketImage" %>
          <% end %>
        </div>
        <div class="col-6 pl-4">
          <h3><%= link_to product.name, url_path %></h3>
          <table>
            <tbody>
              <tr>
                <th class="pr-2 text-right">アーティスト</th>
                <td><%= product.artist.name %></td>
              </tr>
              <tr>
                <th class="pr-2 text-right">レーベル</th>
                <td><%= product.label.name %></td>
              </tr>
              <tr>
                <th class="pr-2 text-right">ジャンル</th>
                <td><%= product.genre.name %></td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="col-4">
          <p class="lead">価格(税込)　¥ <%= product.price.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse %></p>
          <p class="lead">
            <% if product.stock > 0 %>
              <%= "在庫 " + product.stock.to_s %>
            <% else %>
              <span class="text-danger"><%= "在庫がありません" %></span>
            <% end %>
          </p>
          <% if user_signed_in? && product.stock > 0 %>
            <%= form_with model: cart, class: "form-inline align-items-center" do |f| %>
              <%= f.hidden_field :product_id, value: product.id %>
              <%= f.label :quantity, "数量" %>
              <%= f.number_field :quantity, class: "ml-1 mr-2 form-control", min: 1, max: [product.stock, 99].min, value: 1 %>
              <%= f.submit "カート追加", class: "btn btn-primary", "data-toggle" => "modal", "data-target" => "#cartSubmitModal" %>
            <% end %>
          <% else %>
            <% if !user_signed_in? && !admin_signed_in? %>
              <%= link_to "ご購入にはログインが必要です", new_user_session_path, class: "btn btn-danger" %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<div class="container my-5"><div class="row"><div class="mx-auto">
  <%= paginate products, class: "paginate" if products.present? %>
</div></div></div>

<!-- Submit Cart Modal -->
<div class="modal fade" id="cartSubmitModal" tabindex="-1" role="dialog" aria-labelledby="cartSubmitModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="cartSubmitModalLabel">カートに商品を追加しました。</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
        <%= link_to "カートを見る", carts_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/admin_products/_show_product_data.html.erb
<!-- Page header -->
<div class="container">
  <div class="row">
    <div class="col">
      <h2>商品詳細</h2>
    </div>
    <div class="col text-right">
      <% if admin_signed_in? %>
        <%= link_to "編集", edit_admin_product_path(product), class: "btn btn-success" %>
        <a href="#!" class="btn btn-danger" data-toggle="modal" data-target="#deleteAction">削除</a>
      <% end %>
    </div>
  </div>
</div>

<!-- Product data -->
<div class="container">
  <div class="row">
    <div class="col-3">
      <a href="#!" data-toggle="modal" data-target="#jacketView">
        <%= attachment_image_tag product, :jacket_image, fallback: "no_image.png", class: "rounded img-raised" %>
      </a>
    </div>
    <div class="col-5">
      <h3><%= product.name %></h3>
      <table class="mb-3">
        <tbody>
          <tr>
            <th class="pr-2 text-right">アーティスト</th>
            <td><%= product.artist.name %></td>
          </tr>
          <tr>
            <th class="pr-2 text-right">レーベル</th>
            <td><%= product.label.name %></td>
          </tr>
          <tr>
            <th class="pr-2 text-right">ジャンル</th>
            <td><%= product.genre.name %></td>
          </tr>
        </tbody>
      </table>
      <% unless admin_signed_in? %>
        <a href="https://twitter.com/share" class="twitter-share-button" data-size="large" data-text="<%= product.name %>｜NAGANO RECORDS"></a>
      <% end %>
    </div>
    <div class="col-4">
      <p class="lead">価格(税込)　¥ <%= product.price.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse %></p>
      <p class="lead">
        <% if product.stock > 0 %>
          <%= "在庫 " + product.stock.to_s %>
        <% else %>
          <span class="text-danger"><%= "在庫がありません" %></span>
        <% end %>
      </p>
      <% if user_signed_in? && product.stock > 0 %>
        <%= form_with model: cart, class: "form-inline align-items-center" do |f| %>
          <%= f.hidden_field :product_id, value: product.id %>
          <%= f.label :quantity, "数量" %>
          <%= f.number_field :quantity, class: "ml-1 mr-2 form-control", min: 1, max: [product.stock, 99].min, value: 1 %>
          <%= f.submit "カート追加", class: "btn btn-primary", "data-toggle" => "modal", "data-target" => "#cartSubmitModal" %>
        <% end %>
      <% else %>
        <% if !user_signed_in? && !admin_signed_in? %>
          <%= link_to "ご購入にはログインが必要です", new_user_session_path, class: "btn btn-danger" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<!-- Track data -->
<div class="container mt-5">
  <table class="table table-striped">
    <thead class="bg-primary text-white">
      <tr>
        <th>Disc</th>
        <th>#</th>
        <th>曲名</th>
        <th>再生時間</th>
      </tr>
    </thead>
    <tbody>
      <% product.tracks.each do |track| %>
        <tr>
          <td><%= track.disc %></td>
          <td><%= track.number %></td>
          <td><%= track.name %></td>
          <td><%= track.length %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<!-- Product summary -->
<div class="container my-5">
  <h3>商品の紹介</h3>
  <div class="bg-light p-3" style="min-height: 10em;"><%= product.summary %></div>
</div>

<!-- Jacket View Modal -->
<div class="modal fade" id="jacketView" tabindex="-1" role="dialog" aria-labelledby="jacketViewLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="jacketViewLabel"><%= product.name %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= attachment_image_tag product, :jacket_image, fallback: "no_image.png" %>
      </div>
    </div>
  </div>
</div>

<!-- Submit Cart Modal -->
<div class="modal fade" id="cartSubmitModal" tabindex="-1" role="dialog" aria-labelledby="cartSubmitModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="cartSubmitModalLabel">カートに商品を追加しました。</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><%= product.name %> をカートに追加しました。</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
        <%= link_to "カートを見る", carts_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

<!-- Delete Action Modal -->
<div class="modal fade" id="deleteAction" tabindex="-1" role="dialog" aria-labelledby="deleteActionLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-danger" id="deleteActionLabel"><%= product.name %> を削除</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>商品を本当に削除しますか？<br />
        （一旦削除すると元に戻せません。）</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">やめる</button>
        <%= link_to "削除", admin_product_path(product), method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

<!-- Twitter Share Buntton Script -->
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

app/views/admin_products/edit.html.erb
<%= render 'admin_products/edit_product_form', page_title: "商品編集", post_uri: admin_product_path, product: @product, artists: @artists, labels: @labels, genres: @genres %>

app/views/admin_products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-2"></div>
    <div class="col-8 mx-auto">
      <%= form_with url: admin_products_path, method: :get, local: true, class: "row" do |form| %>
        <%= form.select :require, {"商品名": 0, "アーティスト名": 1, "レーベル名": 2, "ジャンル名": 3, "フリーワード検索": 4}, {}, id: "searchSelect", class: "col-3 form-control mx-auto" %>
        <%= form.text_field :word, id: "searchInput", class: "col-6 form-control form-control-lg mx-auto" %>
        <%= form.submit "検索", class: "col-2 btn btn-primary mx-auto", style: "margin: 0;" %>
      <% end %>
    </div>
    <div class="col-2 text-right">
      <%= link_to "商品追加", new_admin_product_path, class: "btn btn-info", style: "margin: 0;" %>
    </div>
  </div>
</div>

<%= render 'admin_products/index_products', products: @products, length: @length, cart: @cart %>

<script>
  // フォームの初期値を反映
  require_param = getParam('require');
  if (!require_param) require_param = 0;
  $('#searchSelect').val(require_param);
  $('#searchInput').val(getParam('word'));

  // クエリパラメータ取得関数
  function getParam(name, url) {
    if (!url) url = window.location.href;
    name = name.replace(/[\[\]]/g, "\\$&");
    var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)")
    var results = regex.exec(url);
    if (!results) return null;
    if (!results[2]) return '';
    return decodeURIComponent(results[2].replace(/\+/g, " "));
  }
</script>

app/views/admin_products/new.html.erb
<%= render 'admin_products/edit_product_form', page_title: "新規商品", post_uri: admin_products_path, product: @product, artists: @artists, labels: @labels, genres: @genres %>

app/views/admin_products/show.html.erb
<%= render 'admin_products/show_product_data', product: @product %>