config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  namespace :users do
    get '' => 'accounts#index'
    resource :unsubscribes, only: [:edit, :destroy]
  end

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  resources :admin_users, only: [:index, :show, :edit, :update, :destroy]

  resources :products, only: [:index, :show]

  resources :admin_products

  resources :carts, only: [:index, :create, :update, :destroy]


  resources :orders, only: [:index, :new, :create, :update]

  namespace :orders do
    get 'check'
  end

  resources :admin_orders, only: [:index, :show, :update]

  resources :addresses, only: [:new, :create, :edit, :update, :destroy]
  post "/order_addresses" => "addresses#order_create", as: "order_addresses"

  resources :consts, only: [:update]
  namespace :consts do
    get 'edit'
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true

  validates :name, presence: true
  validates :zip_code, presence: true
  validates :address, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  def remember_me
    true
  end

  validates :email, presence: true
  # 新しいパスワードと確認用パスワードの一致を検証
  validates :password, confirmation: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :quantity, presence: true
end

app/models/const.rb
class Const < ApplicationRecord

  validates :name, presence: true
  validates :value, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_products
  accepts_nested_attributes_for :order_products, allow_destroy: true

  validates :user_id, presence: true
  validates :zip_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :postage, presence: true
  validates :total, presence: true
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :quantity, presence: true
  validates :price, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :artist
  belongs_to :label
  belongs_to :genre
  has_many :tracks, dependent: :destroy
  has_one :cart, dependent: :destroy
  has_one :order_product

  validates :name, presence: true
  validates :artist_id, presence: true
  validates :label_id, presence: true
  validates :genre_id, presence: true
  validates :price, presence: true
  validates :stock, presence: true
  attachment :jacket_image
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :product

  validates :product_id, presence: true
  validates :disc, presence: true
  validates :number, presence: true
  validates :name, presence: true
  validates :length, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_paranoid

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  def remember_me
    true
  end
  # ユーザー検索メソッド
  def User.search(search)
    if search.present?
      User.where("first_name like ? OR last_name like ? OR (last_name || first_name) like ? OR (last_name || first_name) like?", "%#{search}%","%#{search}%","%#{search}%","%#{search}%")
    else 
      User.all
    end
  end

  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_one :cart, dependent: :destroy
  validates :email, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_ruby, presence: true
  validates :last_name_ruby, presence: true
  validates :phone_number, presence: true, length: { minimum: 10, maximum: 11 }
  validates :zip_code, presence: true, length: { is: 7 }
  validates :address, presence: true
  # 新しいパスワードと確認用パスワードの一致を検証
  validates :password, confirmation: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def index
        @carts = Cart.where(user_id: current_user.id)
        @cart = Cart.where(user_id: current_user.id)
        @put = "put"
        cart_total_price(@carts)
        unless @cart then
        end
        @message = "お客様のショッピングカートに商品はありません。"
    end

    def create
        carts_check = Cart.find_by(user_id: current_user, product_id: product_params[:product_id])
        if carts_check.present?
            carts_check.quantity += product_params[:quantity].to_i
            # @carts_check.quantity = @carts_check.quantity + product_params[:quantity]
            carts_check.save
            redirect_to carts_path
        else
            cart = Cart.new(product_params)
            cart.user_id = current_user.id
            cart.save!
        end
    end

    def update
        cart = Cart.find(params[:id])
        cart.update(product_params)
        redirect_to carts_path
    end

    def destroy
        @cart = Cart.find_by(params[:id])
        @cart.destroy
        redirect_to carts_path
    end


    private
    def product_params
    params.require(:cart).permit(:product_id, :quantity)
    end

    #小計計算メソッド
    def cart_total_price(carts)
        @cart_total_price = 0
        carts.each do |cart|
            cart_subtotal_price = cart.quantity * cart.product.price
            @cart_total_price += cart_subtotal_price
        end
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/adresses_helper.rb
module AdressesHelper
end

app/helpers/carts_helper.rb
module CartsHelper

end

app/helpers/consts_helper.rb
module ConstsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
    def devise_error_messages!
      return "" if resource.errors.empty?

      msg = ""
      messages = resource.errors.full_messages.each do |errmsg|
        msg += errmsg + '\n'
      end

      html = <<-EOF
      <script>
      alert("#{msg}");
      </script>
      EOF
      html.html_safe
    end

    def devise_error_messages?
      resource.errors.empty? ? false : true
    end

  end

app/helpers/orders_helper.rb
module OrdersHelper
    def sum_quantity(orderproducts)
        sum= 0
        orderproducts.each do |orderproduct|
        sum += orderproduct.quantity
        end
        sum
    end
    def sum_price(orderproducts)
        sum= 0
        orderproducts.each do |orderproduct|
        sum += orderproduct.price * orderproduct.quantity
        end
        sum
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/carts/index.html.erb
    <h3 style="margin-left: 100px;"><%= current_user.last_name+current_user.first_name+"さんのカート" %></h3>

    <div class="container">
        <div class="row no-gutters shadow p-3 mb-4 bg-white rounded offset-1" style="display: flex; width: 865px;">
                <% if @cart.present? %>
                <% else %>
                <div style="margin-left: 220px;"><%= @message %></div>
                <% end %>
                <% @carts.each do |cart| %>
                <%= form_with model: cart, method: :patch, url: cart_path(cart), class: "cart_form form-inline" do |f| %>
                    <div style="margin-left: 50px;">
                        <%= attachment_image_tag cart.product, :jacket_image, fallback: "no_image.png",class: "rounded", style: "width: 150px; height: 150px;"%>
                    </div>

                    <div style="width: 200px; height: 100%; margin-left: 60px;">
                        <h4><%= cart.product.name %><br>
                        <h5><%= cart.product.artist.name %></h5></h4>
                    </div>

                    <div style="width: 220px; margin-left: 70px;">
                        <h4>価格(税込)　¥ <%= cart.product.price.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse %></h4><br>
                        <%= f.hidden_field :product_id, value: cart.product_id %>
                        <div class="form-inline">数量　<%= f.number_field :quantity, value:cart.quantity, min: 1, max: 99, class: "form-control cart-quantity", style: "width: 50px;" %>
                            <div style= "width: 40px;"></div>
                            <div class="text-center form-inline">
                                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">削除</button>
                                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">確認</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                        </div>
                                        <div class="modal-body">本当にカートから削除しますか？</div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                <%= link_to  "削除", cart_path(cart.id), method: :'delete', class: "btn btn-danger"%>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            <% end %>
            <% end %>
        </div>
        <% if @cart.present? %>
        <div style="text-align: right; margin-right: 155px;"><h4>小計:　<%= @cart_total_price.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse %>円</h4></div>
        <div style="text-align: right; margin-right: 155px;"><%= link_to "購入手続きへ", new_order_path, class:"btn btn-success btn-lg" %></div>
        <% end %>
    </div>


    <script>
        $('.cart-quantity').on('change', function() {
            console.log($(this))
            Rails.fire($(this).parents('form')[0], 'submit');
});
    </script>